# docker-compose.yml
version: '3.8'
services:
  app:
    container_name: nestjs-app
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=testdb
  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
